### PR TITLE
Update to ruby 2.5.7

### PR DESCRIPTION
**Pull request by jeremywrowe**
This addresses some older dependencies and moves to ruby 2.5.7.

### CODE REVIEW

**Comment by InPermutation** [comment]
**`spreedly-engineering-staging`**:  **heroku-18** will replace **cedar-14** on the next deploy 

Deploying this branch to staging:

```
jacobkrall@corus engineering-blog % git push heroku ruby-2.5.7:master
…
```

**Comment by InPermutation** [comment]
```
remote: -----> Detecting rake tasks
remote:        Could not detect rake tasks
remote:        ensure you can run `$ bundle exec rake -P` against your app
remote:        and using the production group of your Gemfile.
remote:        /tmp/build_56d1f6df8bb3ad60674174d499bc556a/vendor/ruby-2.5.7/lib/ruby/2.5.0/rubygems.rb:284:in `find_spec_for_exe': can't find gem rake (>= 0.a) with executable rake (Gem::GemNotFoundException)
remote:        	from /tmp/build_56d1f6df8bb3ad60674174d499bc556a/vendor/ruby-2.5.7/lib/ruby/2.5.0/rubygems.rb:303:in `activate_bin_path'
remote:        	from /tmp/build_56d1f6df8bb3ad60674174d499bc556a/vendor/ruby-2.5.7/bin/rake:29:in `<main>'```

**Comment by InPermutation** [comment]
Of course now I can't rollback because the old version of Ruby isn't installed on the new heroku-18 stack 🙃

**Comment by InPermutation** [comment]
After adding `rake` to Gemfile,
```
bundle exec middleman build --verbose
```
fails with…
```
== Prerendering CSS
== Request: /stylesheets/style-275ad681.css
== Request: /stylesheets/normalize-483e8167.css
== Finishing Request: stylesheets/normalize-483e8167.css (0.0s)
   identical  build/stylesheets/normalize-483e8167.css
== Finishing Request: stylesheets/style-275ad681.css (0.07s)
       error  build/stylesheets/style-275ad681.css
Error: property "padding-opposite-position" must be followed by a ':'
        on line 702:15 of stdin
>>               padding-opposite-position(left): 0; }

   --------------^

```

**Comment by jeremywrowe** [comment]
@InPermutation It might not be worth putting to much time into this. I stopped at some point because I wanted to rewrite the blog anyway. It's dated looking and has dated dependencies / tech.

**Comment by InPermutation** [comment]
OK, it currently builds on Heroku on the heroku-18 stack.

**Pull request merged**
