### PR TITLE
Engineering blog tweaks

### PR DESCRIPTION
**Pull request by rwdaigle**
I wanted to make a few tweaks to our Engineering blog in preparation for this year's blogging efforts. Building upon @danewesolko's existing work I propose the following additions:

* Use more distinctive fonts ([Oswald/Raleway combo](https://fonts.google.com/specimen/Oswald)). This creates a more stylistic, newspaper, feel: 
* Choose a subtler blue. The blue I chose (#1C81C6) is darker and not so vibrant, but still pulled from the Spreedly home page for consistency.
* Moar whitespace. Developers love the use of whitespace to create a more dramatic style without adding more stuff. Simple, but sophisticated.
* Tightened up the top nav bar. Made it smaller, but more purposeful (with links back to the main site and additional archives/categories for better SEO).
* Removed the use of images from the main page to keep it focused on the title and content, and to make it consistent from article to article.

You can see the proposed changes on the [staging blog](http://spreedly-engineering-staging.herokuapp.com) or this screenshot of the before/after side by side.

@danewesolko @spreedly/developers let me know your thoughts! Not looking for a "like X, don't like Y" review but more a "this is/is not a move in the right direction".

### CODE REVIEW

**Comment by danewesolko** [comment]
@rwdaigle ironic you did this as i was intending on kicking off a project Monday to redesign the engineering blog. i wrote up a document friday and shared with nathaniel. 

https://paper.dropbox.com/doc/Spreedly-Engineering-rGtyefp2eSxHWCuPZanVO

i like the direction you are headed and if the engineering team is fine with it then great. but if you would like i can still follow through with the project and create some comps based on ideas i had.

**Comment by rwdaigle** [comment]
@danewesolko haha, great minds! Sorry if this ruins your plans. Whether to proceed with your proposal or not is up to you. I will say I like having Engineering's tools under Engineering purview. Developers like to tinker so the blog is a great way for us to do so.

If I might suggest, much of what your proposal speaks to I could see applying to the Support site. In fact, your proposal almost feels too structured and formal for a team blog. I think that kind of deliberation might be better invested in support.spreedly.com. Would changing your target still give you a chance to accomplish what you want? Just a suggestion!

Sorry to be a wrench.

**Comment by danewesolko** [comment]
cool no problem. i may still come up with something and show you. but otherwise the design you created is cool. just some ideas.

screen shot 2017-01-22 at 9 49 08 pm

screen shot 2017-01-22 at 9 48 14 pm

**Comment by danewesolko** [comment]
@rwdaigle out of curiosity would you have been open to something like these rough mock ups? one of the concepts i wanted to play on were things that were very developer oriented like monospace type, high contrast and minimal interfaces. these could use polishing but just to get the idea across.

spreedly_engineering_blog-home

spreedly_engineering_blog-article

**Comment by duff** [comment]
Braintree has done [some fixed width font things](https://www.braintreepayments.com/) on their site, but I've never been a huge fan.  I think fixed width is great for code.  Not so great for reading articles (even for just the titles).

I think that one of the reasons that Medium is so popular is because they've done a great job of focusing on typography and the content of the article while removing the noise.

**Comment by danewesolko** [comment]
@duff oh yes i love braintree's branding. it's great. even their videos are fantastic. in my opinion. but good to know you're tastes. medium certainly does have a great eye for design. the way the site has grown over the years and changed is fantastic. they use `Lucida Grande` which is a fantastic font.

check out https://typekit.com/ we have access to this from my CC sub.

good to know tho on the feedback tho.

**Comment by rwdaigle** [comment]
> just some ideas (of ryan's design)

Thanks! I've incorporated these in.

> would you have been open to something like these rough mock ups?

I think these mockups are great! I agree with @duff that sometimes the heavy use of fixed-width fonts can be a bit stark and almost pandering (to devs), but I like the very stylized nature of the mockups. It definitely has an identity.

Going to go ahead and close and push this out. Thanks for the feedback!

**Comment by sdball** [comment]
Wow! The new look is fantastic! 👏

**Pull request closed without merging**
